### PR TITLE
Added a guide on how to selfhost Portaler

### PR DESCRIPTION
**Pull request by ImmortalBrain**
Added a guide on how to selfhost Portaler, both the local and public version

### CODE REVIEW

**Comment by konstantin-lebejko** [comment]
Thanks for the guide. Tested and it's working.

**Comment by konstantin-lebejko** [comment]
Also, after fresh deployment container with PostgeSQL was affected by malware called kdevtmpfsi. 

Here is reference:
https://stackoverflow.com/questions/60151640/kdevtmpfsi-using-the-entire-cpu

So, I would rather recommend not exposing database ports to the host machine that is connected to the Internet, coz no one knows what firewall end-user uses.

**Comment by ImmortalBrain** [comment]
docker-compose.yml changes were not supposed to be included in this PR, that was a mistake on my part so i removed them.

Regarding psql ports being exposed to the Internet - the way i fixed that was by binding containers to 127.0.0.1:port instead (this is what i changed in docker-compose.yml). Not exposing ports to the host machine at all causes issues with proxy_pass.

**Comment by konstantin-lebejko** [comment]
> docker-compose.yml changes were not supposed to be included in this PR, that was a mistake on my part so i removed them.
> 
> Regarding psql ports being exposed to the Internet - the way i fixed that was by binding containers to 127.0.0.1:port instead (this is what i changed in docker-compose.yml). Not exposing ports to the host machine at all causes issues with proxy_pass.

That's weird, because I don't understand how database connectivity might be affected by web-servers proxy_pass.

**Comment by ImmortalBrain** [comment]
> 
> 
> > docker-compose.yml changes were not supposed to be included in this PR, that was a mistake on my part so i removed them.
> > Regarding psql ports being exposed to the Internet - the way i fixed that was by binding containers to 127.0.0.1:port instead (this is what i changed in docker-compose.yml). Not exposing ports to the host machine at all causes issues with proxy_pass.
> 
> That's weird, because I don't understand how database connectivity might be affected by web-servers proxy_pass, as front-end what is hosted on host machine does not send requests directly to the database.

Yes, sorry, what i meant is that not exposing **any** ports (and not just DB ports) leads to issues. Specifically api ports need to be exposed to the host machine so that front-end can access it, everything else works just fine with the bridge connection between containers. There is no reason to expose api ports to the Internet however (hence binding it to 127.0.0.1), unless your webserver is not on your host-machine of course.

When i have the time i'll include separate docker-compose files for both local and public versions and update the guide to use them instead

**Review by mawburn — APPROVED** [review]
This is great. Thank you! Sorry it took me so long to review it, but I definitely appreciate it!

**Pull request merged**
